import type { Listing } from "./types";

/**
 * Realistic Disney Lorcana listings used when no eBay credentials are set,
 * so the marketplace page is viewable offline. Shape matches the eBay
 * Browse API normalization in ebay.ts. URLs point at eBay search for the
 * exact card (real, clickable) until live item URLs are wired in.
 */
const search = (q: string) =>
  `https://www.ebay.com/sch/i.html?_nkw=${encodeURIComponent(
    "Disney Lorcana " + q
  )}`;

export const lorcanaMock: Listing[] = [
  {
    id: "m1",
    title: "Elsa - Spirit of Winter (Legendary)",
    set: "The First Chapter",
    price: 38.5,
    shipping: 0,
    currency: "USD",
    conditionLabel: "Near Mint",
    conditionGroup: "single",
    rarity: "legendary",
    url: search("Elsa Spirit of Winter 42"),
    marketplace: "ebay",
    seller: "inkwell_pulls",
    feedback: 99.8,
  },
  {
    id: "m2",
    title: "Mickey Mouse - Brave Little Tailor (Super Rare)",
    set: "The First Chapter",
    price: 21.0,
    shipping: 0.99,
    currency: "USD",
    conditionLabel: "Lightly Played",
    conditionGroup: "single",
    rarity: "epic",
    url: search("Mickey Mouse Brave Little Tailor 115"),
    marketplace: "ebay",
    seller: "cardvault_us",
    feedback: 99.5,
  },
  {
    id: "m3",
    title: "Hades - Infernal Schemer (Enchanted)",
    set: "Rise of the Floodborn",
    price: 142.0,
    shipping: 4.5,
    currency: "USD",
    conditionLabel: "PSA 10 Gem Mint",
    conditionGroup: "graded",
    rarity: "legendary",
    url: search("Hades Infernal Schemer Enchanted PSA 10"),
    marketplace: "ebay",
    seller: "slabhouse",
    feedback: 100,
  },
  {
    id: "m4",
    title: "The First Chapter — Booster Box (24 Packs, Sealed)",
    set: "The First Chapter",
    price: 199.99,
    shipping: 0,
    currency: "USD",
    conditionLabel: "Factory Sealed",
    conditionGroup: "sealed",
    rarity: "legendary",
    url: search("The First Chapter Booster Box sealed"),
    marketplace: "ebay",
    seller: "tcg_warehouse",
    feedback: 99.9,
  },
  {
    id: "m5",
    title: "Stitch - Rock Star (Super Rare)",
    set: "The First Chapter",
    price: 17.25,
    shipping: 1.25,
    currency: "USD",
    conditionLabel: "Near Mint",
    conditionGroup: "single",
    rarity: "epic",
    url: search("Stitch Rock Star 188"),
    marketplace: "ebay",
    seller: "626experiment",
    feedback: 99.2,
  },
  {
    id: "m6",
    title: "Ursula - Power Hungry (Legendary)",
    set: "The First Chapter",
    price: 12.8,
    shipping: 0,
    currency: "USD",
    conditionLabel: "Near Mint",
    conditionGroup: "single",
    rarity: "legendary",
    url: search("Ursula Power Hungry 222"),
    marketplace: "ebay",
    seller: "poorunfortunate",
    feedback: 98.9,
  },
  {
    id: "m7",
    title: "Rise of the Floodborn — Booster Pack (Sealed)",
    set: "Rise of the Floodborn",
    price: 6.49,
    shipping: 0.99,
    currency: "USD",
    conditionLabel: "Factory Sealed",
    conditionGroup: "sealed",
    rarity: "rare",
    url: search("Rise of the Floodborn booster pack"),
    marketplace: "ebay",
    seller: "floodborn_finds",
    feedback: 99.6,
  },
  {
    id: "m8",
    title: "Maleficent - Monstrous Dragon (Legendary)",
    set: "Rise of the Floodborn",
    price: 9.99,
    shipping: 0.99,
    currency: "USD",
    conditionLabel: "Near Mint",
    conditionGroup: "single",
    rarity: "legendary",
    url: search("Maleficent Monstrous Dragon 194"),
    marketplace: "ebay",
    seller: "dragonhoard",
    feedback: 99.1,
  },
  {
    id: "m9",
    title: "Tinker Bell - Giant Fairy (Super Rare)",
    set: "Into the Inklands",
    price: 8.5,
    shipping: 0,
    currency: "USD",
    conditionLabel: "Near Mint",
    conditionGroup: "single",
    rarity: "epic",
    url: search("Tinker Bell Giant Fairy 36"),
    marketplace: "ebay",
    seller: "neverland_cards",
    feedback: 99.7,
  },
  {
    id: "m10",
    title: "Scrooge McDuck - Richest Duck (Enchanted)",
    set: "Into the Inklands",
    price: 96.0,
    shipping: 3.99,
    currency: "USD",
    conditionLabel: "CGC 9.5",
    conditionGroup: "graded",
    rarity: "legendary",
    url: search("Scrooge McDuck Richest Duck Enchanted"),
    marketplace: "ebay",
    seller: "moneybin",
    feedback: 100,
  },
  {
    id: "m11",
    title: "Into the Inklands — Illumineer's Trove (Sealed)",
    set: "Into the Inklands",
    price: 44.95,
    shipping: 0,
    currency: "USD",
    conditionLabel: "Factory Sealed",
    conditionGroup: "sealed",
    rarity: "epic",
    url: search("Into the Inklands Illumineer's Trove"),
    marketplace: "ebay",
    seller: "tcg_warehouse",
    feedback: 99.9,
  },
  {
    id: "m12",
    title: "Belle - Strange but Special (Super Rare)",
    set: "Ursula's Return",
    price: 7.2,
    shipping: 0.99,
    currency: "USD",
    conditionLabel: "Lightly Played",
    conditionGroup: "single",
    rarity: "epic",
    url: search("Belle Strange but Special 36"),
    marketplace: "ebay",
    seller: "tale_as_old",
    feedback: 98.5,
  },
  {
    id: "m13",
    title: "Ariel - Spectacular Singer (Enchanted)",
    set: "The First Chapter",
    price: 168.0,
    shipping: 5.0,
    currency: "USD",
    conditionLabel: "PSA 10 Gem Mint",
    conditionGroup: "graded",
    rarity: "legendary",
    url: search("Ariel Spectacular Singer Enchanted PSA 10"),
    marketplace: "ebay",
    seller: "underthesea",
    feedback: 100,
  },
  {
    id: "m14",
    title: "Mufasa - Betrayed Leader (Rare)",
    set: "Ursula's Return",
    price: 1.49,
    shipping: 0.99,
    currency: "USD",
    conditionLabel: "Near Mint",
    conditionGroup: "single",
    rarity: "rare",
    url: search("Mufasa Betrayed Leader"),
    marketplace: "ebay",
    seller: "pridelands",
    feedback: 99.0,
  },
  {
    id: "m15",
    title: "Jafar - Wickedly Powerful (Legendary)",
    set: "Reign of Jafar",
    price: 11.0,
    shipping: 0,
    currency: "USD",
    conditionLabel: "Near Mint",
    conditionGroup: "single",
    rarity: "legendary",
    url: search("Jafar Wickedly Powerful"),
    marketplace: "ebay",
    seller: "cave_of_wonders",
    feedback: 99.4,
  },
  {
    id: "m16",
    title: "Shimmering Skies — Booster Box (Sealed)",
    set: "Shimmering Skies",
    price: 119.99,
    shipping: 0,
    currency: "USD",
    conditionLabel: "Factory Sealed",
    conditionGroup: "sealed",
    rarity: "legendary",
    url: search("Shimmering Skies booster box sealed"),
    marketplace: "ebay",
    seller: "skybound_tcg",
    feedback: 99.8,
  },
  {
    id: "m17",
    title: "Genie - On the Job (Super Rare)",
    set: "Reign of Jafar",
    price: 5.75,
    shipping: 0.99,
    currency: "USD",
    conditionLabel: "Near Mint",
    conditionGroup: "single",
    rarity: "epic",
    url: search("Genie On the Job"),
    marketplace: "ebay",
    seller: "threewishes",
    feedback: 98.8,
  },
  {
    id: "m18",
    title: "Bolt - Superdog (Promo, Foil)",
    set: "Promo",
    price: 3.25,
    shipping: 0.99,
    currency: "USD",
    conditionLabel: "Near Mint",
    conditionGroup: "single",
    rarity: "uncommon",
    url: search("Bolt Superdog promo foil"),
    marketplace: "ebay",
    seller: "promo_pulls",
    feedback: 99.3,
  },
];
